name: Build and Release Linux Kernel and Initramfs

on:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Set up Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc git wget cpio flex bison libssl-dev gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu

  build-buildroot:
    name: Build Initramfs
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Buildroot
        env:
          PLATFORM: qemu-aarch64-virt
          ARCH: aarch64
        run: |
          make setup
          make buildroot

      - name: Archive Initramfs
        run: |
          tar czf initramfs-${{ env.PLATFORM }}.tar.gz -C wrkdir rootfs_${{ env.ARCH }}.cpio

      - name: Create Initramfs Release
        id: create_buildroot_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: initramfs-${{ env.PLATFORM }}
          release_name: Initramfs for ${{ env.PLATFORM }}
          draft: false
          prerelease: false

      - name: Upload Initramfs
        id: upload-buildroot-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_buildroot_release.outputs.upload_url }}
          asset_path: ./initramfs-${{ env.PLATFORM }}.tar.gz
          asset_name: initramfs-${{ env.PLATFORM }}.tar.gz
          label: Initramfs for ${{ env.PLATFORM }}

  build-linux:
    name: Build Linux Kernel
    runs-on: ubuntu-latest
    needs: [setup-environment, build-buildroot]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Linux Kernel
        env:
          PLATFORM: qemu-aarch64-virt
          ARCH: aarch64
        run: |
          make setup
          make linux

      - name: Archive Linux Kernel
        run: |
          tar czf linux-kernel-${{ env.PLATFORM }}.tar.gz -C wrkdir Image-${{ env.PLATFORM }}

      - name: Create Linux Kernel Release
        id: create_linux_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: linux-${{ env.PLATFORM }}
          release_name: Linux Kernel for ${{ env.PLATFORM }}
          draft: false
          prerelease: false

      - name: Upload Linux Kernel
        id: upload-linux-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_linux_release.outputs.upload_url }}
          asset_path: ./linux-kernel-${{ env.PLATFORM }}.tar.gz
          asset_name: linux-kernel-${{ env.PLATFORM }}.tar.gz
          label: Linux Kernel for ${{ env.PLATFORM }}
